### PR TITLE
Proposal indexing internal deps

### PR DESCRIPTION
**Pull request by BurnedMarshal**
Depends on #17 

#### List of Changes

Removed single export on modules
Add index file for remap exports in Repo, Service and Controller

#### Motivation and Context

To handle in a more concise way ed improve the developer experience writing new methods

#### How Has This Been Tested?

unit test

#### Types of changes

- [X] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by arcogabbo** [comment]
does this PR depends on #17?

**Comment by BurnedMarshal** [comment]
> does this PR depend on #17?

The base branch is [IOPID-1797-unit-test-getsession](https://github.com/pagopa/io-auth-n-identity-domain/tree/IOPID-1797-unit-test-getsession) so de dependency is implicit.

**Review by gquadrati — COMMENTED** [review]
🚀

**Review by gquadrati — APPROVED** [review]
🚀

**Pull request merged**
